insert into Route_group (Destination) values ('3 Monument Drive');
insert into Route_group (Destination) values ('713 Corry Way');
insert into Route_group (Destination) values ('9 Calypso Circle');
insert into Route_group (Destination) values ('52 Hoepker Place');
insert into Route_group (Destination) values ('558 Banding Way');
insert into Route_group (Destination) values ('94 Johnson Place');
insert into Route_group (Destination) values ('61 Fremont Road');
insert into Route_group (Destination) values ('515 Carey Point');
insert into Route_group (Destination) values ('97 Shasta Point');
insert into Route_group (Destination) values ('863 Weeping Birch Place');
insert into Route_group (Destination) values ('01 Buena Vista Court');
insert into Route_group (Destination) values ('4934 8th Drive');
insert into Route_group (Destination) values ('360 Cardinal Park');
insert into Route_group (Destination) values ('13 Carpenter Trail');
insert into Route_group (Destination) values ('8278 Burning Wood Parkway');
insert into Route_group (Destination) values ('8 Hallows Junction');
insert into Route_group (Destination) values ('8 Rowland Hill');
insert into Route_group (Destination) values ('877 Delaware Park');
insert into Route_group (Destination) values ('3028 Dexter Junction');
insert into Route_group (Destination) values ('73342 Lunder Point');
